### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeAttribute' of null

### ISSUE THREAD

**Issue by knowuh** [concord-consortium/building-models#202]
View details in Rollbar: [https://rollbar.com/concordconsortium/Sage/items/506/](https://rollbar.com/concordconsortium/Sage/items/506/)

```

TypeError: Cannot read property 'removeAttribute' of null
  File "<anonymous>", line 5, in [anonymous]
  File "<anonymous>", line 20, in [anonymous]
```

**Comment by ranaclyde** [comment]
Same problem here. For some reason Chrome ADBlock (not plus) was the cause. (Font: http://stackoverflow.com/questions/38143879/cannot-read-property-removeattribute-of-null-cant-find-source-of-it)

**Comment by sfentress** [comment]
Huh, is RollBar catching all errors that appear in the console, regardless of the source?

Because, if so, it's true, this error is almost certainly caused by AdBlock, not the site. I get that error in my console on every site I go to. Is there a way to ask RollBar to silence that one, @knowuh?

**Comment by sfentress** [comment]
Indeed, the `line 5, in [anonymous]` matches that, because it's being thrown from line 5 of the Chrome extension.

**Comment by knowuh** [comment]
Nice hunting. I just muted that error for sage.  I feel like it should be globally muted though.

**Comment by knowuh** [comment]
Do we want to possibly close this issue then?

**Comment by sfentress** [comment]
Thanks @ranaclyde for the tip!

**Comment by pushprajsingh05** [comment]
I don't think its adblock issue. I am launching chrome using Selenium, which doesn't have any chrome-extension. Now I try to execute following piece of code on this page http://jsfiddle.net/343Rb/ 
```
public JavascriptExecutor executeJS() {
    JavascriptExecutor jsexec = (JavascriptExecutor).driver;
    return jsexec;
}

executeJS().executeScript("document.getElementById('myInput').removeAttribute('readonly')");
```
and it gave me same error ` Cannot read property 'removeAttribute' of null`

**Comment by ManoharKoya** [comment]
Hi @pushprajsingh05 facing the same issue in chrome using Selenium, it will be helpful if you mention the solution for the same.
