### ISSUE TITLE
TestRollbarError: testing window.onerror

### ISSUE THREAD

**Issue by knowuh** [concord-consortium/building-models#307]
View details in Rollbar: [https://rollbar.com/concordconsortium/Sage/items/950/](https://rollbar.com/concordconsortium/Sage/items/950/)

```

TestRollbarError: testing window.onerror
  File "http://127.0.0.1:8080/sage.html", line unknown, in [anonymous]
```

**Comment by kswenson** [comment]
This was a test of Rollbar configuration changes.
